vim.pack.add({ { src = "https://github.com/folke/which-key.nvim" } })
require('which-key').setup {
    preset = "modern",
    spec = {
        { "<Leader>d",      group = "Trouble - Debug" },
        { "<Leader>b",      group = "Buffer" },
        { "<Leader>c",      group = "Code?" },
        { "<Leader>A",      group = "Parrot AI" },
        { "<Leader>f",      group = "FuzzyScope" },
        { "F",              group = "JumpF[i]nd" },
        { "<C-o>",          group = "Available commands" },
        { "<Leader>t",      group = "[T]" },
        { "<Leader>s",      group = "Search" },
        { "<Leader>g",      group = "Git" },
        { "<Leader>f",      group = "Fuzzy" },
        { "<Leader>u",      group = "Utilities" },
        { "<Leader>ts",     group = "TreeSitter" },
        { "g",              group = "Goto" },
        { "z",              group = "Toggle" },
        { "<Leader>",       group = "Main()" },
        { "]",              group = "JumpTo" },
        { "[",              group = "BackTo" },
        { "<localleader>",  group = "Sub()" },
        { "<localleader>n", group = "Neorg" },
        { "gr",             group = "Native actions" },
        { "<A-a>",          group = "AI" },
        { "<A-e>",          group = "Fast Wrap Autopairs" },
    },
}
